<a href="https://colab.research.google.com/github/Archana-Tharammal/Introduction-to-Data-Science/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
my_list=[1,5,3,4]
my_list

[1, 5, 3, 4]

In [ ]:
import numpy as np
np.array(my_list)

array([1, 5, 3, 4])

In [ ]:
my_matrix=[[1,2,3],[4,5,1],[5,4,6]]
my_matrix

[[1, 2, 3], [4, 5, 1], [5, 4, 6]]

In [ ]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 1],
       [5, 4, 6]])

In [ ]:
np.arange(0,10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [ ]:
np.linspace(0,10,25)

array([ 0.        ,  0.41666667,  0.83333333,  1.25      ,  1.66666667,
        2.08333333,  2.5       ,  2.91666667,  3.33333333,  3.75      ,
        4.16666667,  4.58333333,  5.        ,  5.41666667,  5.83333333,
        6.25      ,  6.66666667,  7.08333333,  7.5       ,  7.91666667,
        8.33333333,  8.75      ,  9.16666667,  9.58333333, 10.        ])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.random.rand(2)

array([0.83681502, 0.86888879])

In [ ]:
np.random.rand(5,5)

array([[0.48975086, 0.26217354, 0.75588788, 0.80927633, 0.68932487],
       [0.67122869, 0.0432981 , 0.84542767, 0.65621342, 0.64767059],
       [0.42112612, 0.42513386, 0.46025421, 0.54572558, 0.83556818],
       [0.60673252, 0.71372849, 0.54983712, 0.42604251, 0.59822498],
       [0.929056  , 0.06273141, 0.5785684 , 0.61175571, 0.35705916]])

In [ ]:
np.random.randn(2)

array([0.01576371, 1.49602143])

In [ ]:
np.random.randn(5,5)

array([[-0.4514445 , -0.64328089,  0.67582834,  0.20766335, -0.06412298],
       [ 0.25895165, -0.15709965, -1.53111226,  0.24513986, -0.71572886],
       [-0.30811137,  0.69626084, -1.14010098, -0.37266451, -2.21046358],
       [-0.26055315,  0.91930904, -1.0637774 , -0.09403619, -2.78590602],
       [ 1.0067136 , -1.44759542, -1.41445456, -0.60893219,  0.95241603]])

In [ ]:
np.random.randint(1,100)

21

In [ ]:
np.random.randint(1,100,3)

array([65, 89, 19])

In [ ]:
arr=np.arange(25)
ranarr=np.random.randint(0,50,10)


In [ ]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
ranarr

array([19, 27,  8, 47, 16, 18, 17, 40, 46, 35])

In [ ]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
ranarr


array([19, 27,  8, 47, 16, 18, 17, 40, 46, 35])

In [ ]:
ranarr.max()

47

In [ ]:
ranarr.argmax()

3

In [ ]:
ranarr.min()

8

In [ ]:
ranarr.argmin()

2

In [ ]:
arr.shape

(25,)

In [ ]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
arr.reshape(1,25).shape

(1, 25)

In [ ]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [ ]:
arr.reshape(25,1).shape

(25, 1)

In [ ]:
arr.dtype


dtype('int64')