<a href="https://colab.research.google.com/github/Archana-Tharammal/Introduction-to-Data-Science/blob/main/NumPy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr=np.arange(0,11)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr[8]

8

In [ ]:
arr[1:5]

array([1, 2, 3, 4])

In [ ]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [ ]:
arr[0:5]=100

In [ ]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [ ]:
arr=np.arange(0,11)

In [ ]:
slice_of_arr=arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [ ]:
slice_of_arr[:]=99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [ ]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [ ]:
arr_copy=arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [ ]:
arr_2d=np.array(([5,10,5],[20,30,40],[10,25,100]))
arr_2d

array([[  5,  10,   5],
       [ 20,  30,  40],
       [ 10,  25, 100]])

In [ ]:
arr_2d[1]

array([20, 30, 40])

In [ ]:
arr_2d[1][0]

20

In [ ]:
arr_2d[1,0]

20

In [ ]:
arr_2d[:2,1:]

array([[10,  5],
       [30, 40]])

In [ ]:
arr_2d[2]

array([ 10,  25, 100])

In [ ]:
arr_2d[2,:]

array([ 10,  25, 100])

In [ ]:
arr2d=np.zeros((10,10))

In [ ]:
arr_length=arr2d.shape[1]

In [ ]:
for i in range(arr_length):
  arr2d[i]=i
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [ ]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [ ]:
arr2d[[6,7,5,3]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.]])

In [ ]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
bool_arr=arr>4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
x=2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])